#!/bin/bash

# setup everything for using the virtualenv commands
source `which virtualenvwrapper.sh`

# establish the correct python virtualenv
workon web-app

# startup python & pass it our configuration
python piguard.py --conf config.json
